# Generated by Django 5.1.5 on 2025-02-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_issuereport_upvotes_issuecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_plate_number',
            new_name='plate_number',
        ),
        migrations.RemoveField(
            model_name='parkingticket',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='parkingticket',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='parkingticket',
            name='parking_lot_id',
        ),
        migrations.RemoveField(
            model_name='parkingticket',
            name='vehicle_plate_number',
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('used', 'used')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_tickets', to='portal.vehicle'),
        ),
        migrations.DeleteModel(
            name='ParkingPayment',
        ),
    ]
