# Generated by Django 5.1.5 on 2025-02-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_make_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payers', to='portal.city'),
        ),
        migrations.AlterField(
            model_name='taxbill',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('overdue', 'overdue')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taxexemption',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='portal.taxpayer'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payer', to='portal.business'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payer', to='portal.property'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='total_tax_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payer', to='portal.vehicle'),
        ),
        migrations.DeleteModel(
            name='TaxPayment',
        ),
    ]
