# Generated by Django 5.1.5 on 2025-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_taxpayer_city_alter_taxbill_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial'), ('industrial', 'industrial'), ('agricultural', 'agricultural'), ('institutional', 'institutional'), ('vacant', 'vacant'), ('other', 'other')], max_length=50, null=True),
        ),
    ]
