# Generated by Django 5.1.5 on 2025-02-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.city'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='renewal_period',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('duty', 'duty(once)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='type',
            field=models.CharField(choices=[('property', 'property'), ('business', 'business'), ('vehicle', 'vehicle'), ('housing', 'housing')], max_length=100),
        ),
    ]
