# Generated by Django 5.1.5 on 2025-02-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_user_city_alter_tax_renewal_period_alter_tax_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermeter',
            name='type',
        ),
    ]
