# Generated by Django 5.1.5 on 2025-02-06 16:35

import portal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_announcement_display_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, default=portal.models.Announcement.get_24_hour_date, null=True),
        ),
    ]
