# Generated by Django 5.1.5 on 2025-02-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_vehicle_approval_status_vehicle_city_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleapproval',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.vehicle', unique=True),
        ),
    ]
