# Generated by Django 5.1.5 on 2025-02-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_vehicleapproval_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleapproval',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.vehicle'),
        ),
    ]
