# Generated by Django 5.1.5 on 2025-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_vehicleapproval_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingticket',
            name='created_at',
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='issued_length',
            field=models.CharField(choices=[('30min', '30 Minutes'), ('1hr', '1 Hour'), ('2hr', '2 Hours'), ('3hr', '3 Hours')], default='30min', max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('used', 'Used')], default='active', max_length=10),
        ),
    ]
