# Generated by Django 5.1.5 on 2025-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_remove_parkingticket_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=10),
        ),
    ]
