# Generated by Django 5.1.5 on 2025-02-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_parkingticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('used', 'Used')], default='active', max_length=10),
        ),
    ]
