# Generated by Django 5.1.5 on 2025-02-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_parkingticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parking_tickets', to='portal.city'),
        ),
    ]
