# Generated by Django 5.1.5 on 2025-02-12 10:50

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_parkingticket_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='city',
            new_name='city_registered',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='business',
            name='purpose',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='business',
            name='reg_num',
            field=models.CharField(default=portal.models.Business.generate_registration_number, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('individual', 'individual'), ('corporate', 'corporate'), ('partnership', 'partnership'), ('joint_venture', 'joint venture'), ('limited_liability_company', 'limited liability company')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to='portal.business'),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='issue_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='license_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='type',
            field=models.CharField(choices=[('business_permit', 'Business Permit'), ('business_registration', 'Business Registration'), ('sign_permit', 'Sign Permit'), ('liquor_license', 'Liquor License'), ('food_permit', 'Food Permit'), ('tax_permit', 'Tax Permit'), ('fire_permit', 'Fire Permit'), ('health_permit', 'Health Permit'), ('public_health_permit', 'Public Health Permit')], max_length=50),
        ),
    ]
