# Generated by Django 5.1.5 on 2025-02-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_rename_city_business_city_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslicense',
            name='license_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
