# Generated by Django 5.1.5 on 2025-02-13 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_businesslicense_license_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslicense',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessLicenseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=50)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.businesslicense')),
            ],
        ),
    ]
