# Generated by Django 5.1.5 on 2025-02-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_businesslicense_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='reg_num',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active'), ('suspended', 'Suspended')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('partnership', 'Partnership'), ('joint_venture', 'Joint Venture'), ('limited_liability_company', 'Limited Liability Company')], max_length=50),
        ),
    ]
