# Generated by Django 5.1.5 on 2025-02-14 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_business_reg_num_alter_business_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
