# Generated by Django 5.1.5 on 2025-02-14 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_business_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslicense',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
