# Generated by Django 5.1.5 on 2025-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_businesslicense_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueComment',
            new_name='AnnouncementComment',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='property',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('water', 'water'), ('electricity', 'electricity'), ('sewer', 'sewer'), ('garbage', 'garbage'), ('road', 'road'), ('other', 'other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('resolved', 'resolved'), ('active', 'active')], default='pending', max_length=50),
        ),
    ]
