# Generated by Django 5.1.5 on 2025-02-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_rename_issuecomment_announcementcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementcomment',
            name='issue_report',
        ),
        migrations.AddField(
            model_name='announcement',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_comments', to='portal.announcement'),
        ),
        migrations.AddField(
            model_name='announcementcomment',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.city'),
        ),
    ]
