# Generated by Django 5.1.5 on 2025-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_remove_announcementcomment_issue_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires',
            field=models.BooleanField(default=False),
        ),
    ]
