# Generated by Django 5.1.5 on 2025-02-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_announcement_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='end_date',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_date',
        ),
    ]
