databases:
  - name: council_portal
    plan: free
    databaseName: council_portal
    user: taona

services:
  - type: web
    plan: free
    name: council-portal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn portal.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: council_portal
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4